HEADER:
  label: "Blog"

POSTS:
  - title: "Probabilistic Models in Machine Learning"
    category: "Probabilistic Model"
    subtitle: "Some Methods for Working with Probabilistic Models in Machine Learning"
    published: "2024-08-23"
    image: "config/assets/posts/blog-1.jpg"
    url: "https://hackmd.io/6hzffecmTHWtt5xd8a8b2Q?view"
  - title: "Building a Virtual Bank Consultant with LLM and Speech Processing"
    category: "LLM & Speech Processing"
    subtitle: "A real-time, multi-agent system leveraging LLMs and Whisper for live banking conversation analysis and recommendations."
    published: "2026-01-04"
    image: "config/assets/posts/blog7.png"
    url: "https://hackmd.io/@jjleeblogger/S1lHHWl8Ze"

  - title: "Sampling and Estimation Problems in Probability"
    category: "Probabilistic Model"
    subtitle: "In this article, I address a important topic because it contains foundational knowledge that helps you better understand two methods: MLE and MAP (two extremely important methods for probabilistic models in machine learning)."
    published: "2025-01-28"
    image: "config/assets/posts/blog5.png"
    url: "https://hackmd.io/vb28ZpB8QlWRa1ETqG1bfQ"

  - title: "An End-to-End MLOps System for Real Estate Price Prediction with LLM-based Interaction"
    category: "LLM & MLOps & ML"
    subtitle: "From Large-Scale Data Crawling, Feature Store, Automated Training to LLM Function-Calling Chatbot"
    published: "2024-12-24"
    image: "config/assets/posts/blog2.jpg"
    url: "https://hackmd.io/0-brqldVQrGaCG-NuUDszQ"

  - title: "Large Margin Nearest Neighbor (LMNN) Algorithm"
    category: "Metric Learning & Opt"
    subtitle: "A method to improve KNN by learning a custom distance metric that separates target neighbors from impostors"
    published: "2025-10-11"
    image: "config/assets/posts/blog9.png"
    url: "https://hackmd.io/HiXaJa-OTducFRgL0UCa0Q?view"


  - title: "Action Recognition with Graph Neural Networks"
    category: "Computer Vision"
    subtitle: "A deep dive into modeling human actions in videos using ST-GCN, LSTM, and attention mechanisms."
    published: "2023-09-25"
    image: "config/assets/posts/blog4.jpg"
    url: "https://hackmd.io/F_mTx5EzRbeRjQim76g9VQ?view"

  - title: "Understanding the CART Algorithm in Decision Tree Construction"
    category: "Machine Learning"
    subtitle: "A comprehensive guide to the CART algorithm, Gini index, and practical implementation in Python for effective classification."
    published: "2023-05-21"
    image: "config/assets/posts/blog8.png"
    url: "https://hackmd.io/gZy4uryPRK6TvtrS2dxxUQ?view"

  - title: "RealEstate Serving System"
    category: "System Design"
    subtitle: "A system to collect, store, and process real estate data from multiple sources. Supports fast search and displays detailed property information with images for end users"
    published: "2024-05-17"
    image: "config/assets/posts/blog6.jpeg"
    url: "https://hackmd.io/br4IYmHMQRu6MlycQ0li3w?view"
