HEADER:
  label: "Projects"

PROJECTS:
  - title: "Robot Optimization"
    category: "Robot"
    image: "config/assets/posts/blog20.png"
    url: "https://github.com/JJLEE-20194099/Robot-Optimization/"

  
  - title: "Bank Agent Advisor - AI Agent Competition - Top2"
    category: "LLM"
    image: "config/assets/posts/blog3.png"
    url: "https://github.com/JJLEE-20194099/virtual-bank-agentic-consultant"

  - title: "RealEstate Price Prediction"
    category: "AI"
    image: "config/assets/posts/blog2.jpg"
    url: "https://github.com/JJLEE-20194099/BKPriceSystem"
  - title: "IMDB Film Recommender System"
    category: "AI"
    image: "config/assets/posts/blog12.png"
    url: "https://github.com/JJLEE-20194099/imdb-recommender-system"

  - title: "Kaggle Competition Expert"
    category: "Competition"
    image: "config/assets/posts/blog15.png"
    url: "https://www.kaggle.com/jjleesunny"

  - title: "3D Reconstruction (Fast3R Model)"
    category: "Computer Vision"
    image: "config/assets/posts/blog13.png"
    url: "https://lundmarkj.github.io/DT082A-Project/"

  - title: "Blog: Machine Learning from Hero to Zero"
    category: "Teaching / Blog"
    image: "config/assets/posts/blog14.png"
    url: "https://github.com/JJLEE-20194099/machine_learning_from_zero_to_hero_course"

  - title: "Virtual Try-on CLothes (AI Summer School - Best Presentation Award)"
    category: "Computer Vision"
    image: "config/assets/posts/blog10.jpg"
    url: "https://youtube.com/clip/UgkxwuUsXmVFNL_-LzixNfgGOOPf1S8LCcEL?si=vPAFxJSB6KN2TF8T"

  - title: "Junction Hackathon - Using AI to detect Phishing Website & Email"
    category: "AI"
    image: "config/assets/posts/blog16.jpg"
    url: "https://docs.google.com/document/d/13nQg2vRDk9QwBF8xJ8C930bkOicY_gYWWZlioiC42-M/edit?usp=sharing"

  - title: "Top 3 Yody Hackathon - Clothes Recommendation"
    category: "AI"
    image: "config/assets/posts/blog17.jpg"
    url: "#"

  - title: "Top 2 Student Creative Idea Challenge"
    category: "Application"
    image: "config/assets/posts/blog18.jpg"
    url: "#"
  - title: "Top 1 NA Hackathon - Cloth Detection & 3D Try-on Cloth"
    category: "AI"
    image: "config/assets/posts/blog19.jpeg"
    url: "#"
